-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY6Zb/TxG+7/IekTB
OYjBSNIlOeOyM10L24I9MdHjTxWgCgYIKoZIzj0DAQehRANCAATqzDb0JO2EdgW1
JwLIaHJTrosli0CPV1TMWoukvyoTpomJquspSJKsK/iHskjekJULNvYiOnCDvmZC
hkrwAnmk
-----END PRIVATE KEY-----