name: Build Flutter ios

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-mac.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - run: export APP_STORE_CONNECT_ISSUER_ID=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
    - run: export APP_STORE_CONNECT_KEY_IDENTIFIER=${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }}
    
    - run: pip3 install codemagic-cli-tools
    
    - run: keychain initialize
    - run: app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --private-key=AuthKey_YGLT83UMQ9.p8.p8 --platform IOS --type IOS_APP_ADHOC --certificate-key=cert_key --create
    - run: keychain add-certificates
    - run: xcode-project use-profiles
    - run: flutter packages pub get
    - run: find . -name "Podfile" -execdir pod install \;

    - run: flutter pub get
    - run: flutter build ios --release --export-options-plist=$HOME/export_options.plist
    
    - run: appcenter login --token ${{secrets.APP_CENTER_TOKEN}}
    - run: appcenter distribute release -f $(find $(pwd) -name "*.ipa") \
                                       -g Collaborators \
                                       --app k-strathdee/Flutter-CICD
