name: Build Flutter UWP

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-windows.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - run: flutter build windows -v

    - name: Perform a Pester test from the command-line
      shell: pwsh
      run: Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe" -WindowStyle Hidden

    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build AppiumTest
    - name: Test
      run: dotnet test AppiumTest
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: AppiumTest/Screenshots/screenshot.png