name: Build Flutter ios

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-mac.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11
    steps:
    
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.0'
    
    - name: Setup iOS Code Signing Resources
      shell: bash
      run: |
        pip3 install codemagic-cli-tools
        keychain initialize
        app-store-connect fetch-signing-files $(xcode-project detect-bundle-id) --private-key="${{ secrets.APP_STORE_CONNECT_PRIVATE_KEY }}" --platform IOS --type IOS_APP_ADHOC --certificate-key="${{ secrets.CERT_KEY }}" --issuer-id=${{ secrets.APP_STORE_CONNECT_ISSUER_ID }} --key-id=${{ secrets.APP_STORE_CONNECT_KEY_IDENTIFIER }} --create
        keychain add-certificates
        xcode-project use-profiles

    - name: Fetch pub packages
      shell: bash
      run: |
        flutter packages pub get
        find . -name "Podfile" -execdir pod install \;
        flutter pub get

    - name: Build ios release
      shell: bash
      run: |
        flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    

    - run: appcenter login --token ${{secrets.APP_CENTER_TOKEN}}
    - run: appcenter distribute release -f $(find $(pwd) -name "*.ipa") -g Collaborators --app k-strathdee/Flutter-CICD
