name: Build Flutter UWP

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-windows.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Launch winappdriver
      shell: pwsh
      run: | 
        Start-Process -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
    - run: flutter config --enable-windows-desktop
    - run: flutter test integration_test/counter_test.dart -d windows
    - run: flutter build windows
