name: Build Flutter UWP

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/flutter-windows.yml' 
      - 'src/**'

  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: dev
    - run: flutter config --enable-windows-uwp-desktop
    - run: flutter build winuwp -v

    - name: Distribute Windows UWP
      shell: bash
      run: |
        npm install -g appcenter-cli
        appcenter login --token ${{secrets.APP_CENTER_TOKEN}}
        appcenter distribute release -f $(find $(pwd) -name "*.msix") -g Collaborators --app k-strathdee/Flutter-CICD-UWP
